# Created with YamlCreate.ps1 v2.1.3 using InputObject 🤖 =QUSU.7-2-6
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.2.0.schema.json

PackageIdentifier: ActivityWatch.ActivityWatch
PackageVersion: 0.12.0
InstallerLocale: en-US
Platform:
- Windows.Desktop
MinimumOSVersion: 10.0.0.0
InstallerType: inno
InstallModes:
- interactive
- silent
- silentWithProgress
UpgradeBehavior: install
ReleaseDate: 2022-08-31
Installers:
- Architecture: x86
  Scope: user
  InstallerUrl: https://github.com/ActivityWatch/activitywatch/releases/download/v0.12.0/activitywatch-v0.12.0-windows-x86_64-setup.exe
  InstallerSha256: DEE81128C4DA2E0649B3EC6BFCDCFDF3556E44E5EA14CA6BFB8B87D0EB92F48F
  InstallerSwitches:
    Custom: /norestart /closeapplications /currentuser
- Architecture: x86
  Scope: machine
  InstallerUrl: https://github.com/ActivityWatch/activitywatch/releases/download/v0.12.0/activitywatch-v0.12.0-windows-x86_64-setup.exe
  InstallerSha256: DEE81128C4DA2E0649B3EC6BFCDCFDF3556E44E5EA14CA6BFB8B87D0EB92F48F
  InstallerSwitches:
    Custom: /norestart /closeapplications /allusers
ManifestType: installer
ManifestVersion: 1.2.0
